apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: mc2019
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: pddninc239
  POSTGRES_HOST: postgres
